<a href="https://colab.research.google.com/github/yaser2532/python-basics-/blob/main/Pandas_Assignment_Day_10(completed).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [2]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [3]:
a = pd.Series([100, 200, 300, 400])
print(a)

0    100
1    200
2    300
3    400
dtype: int64

Print a, and data type

In [4]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [5]:
print(a[2])

300

What are the values of index for series a?

In [9]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [ ]:
a.index = ['c', 'a', 'b', 'd']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [ ]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [ ]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [ ]:
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [ ]:
a = pd.concat([a, b])

In [ ]:
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [ ]:
a = a.sort_values(ascending=False)

In [ ]:
print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [ ]:
df = pd.DataFrame(a)
print(df)

     0
e  800
f  450
d  400
b  300
a  200
c  100
g  100

In [ ]:
df

     0
e  800
f  450
d  400
b  300
a  200
c  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [ ]:
print(df.shape)
# It mostly implies that the DataFrame has 7 rows and 1 column in this case we have a table with 7 rows and 1 coloum.

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [ ]:
print(df.index)
# Yes, the index of the DataFrame is the same as the series 'a' because previouly we changed the index type of the df.

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [ ]:
print('DataFrame Head:')
print(df.head())
print('\nDataFrame Tail:')
print(df.tail())
# head() represents the first few rows (default 5) and tail() represents the last few rows (default 5).

DataFrame Head:
     0
e  800
f  450
d  400
b  300
a  200

DataFrame Tail:
     0
d  400
b  300
a  200
c  100
g  100

In [ ]:
# Extra space to show head/tail
df.head()

     0
e  800
f  450
d  400
b  300
a  200

Rename the column of the dataframe as 'points'

In [ ]:
df = df.rename(columns={0: 'points'})
print(df)

   points
e     800
f     450
d     400
b     300
a     200
c     100
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [ ]:
np.random.seed(42)
fruits = np.random.choice(['orange', 'mango', 'apple'], size=7)

In [ ]:
fruits = pd.Series(fruits)
print(fruits)

0     apple
1    orange
2     apple
3     apple
4    orange
5    orange
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [ ]:
fruits.index = df.index
print(fruits)

e     apple
f    orange
d     apple
b     apple
a    orange
c    orange
g     apple
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [ ]:
df['fruits'] = fruits

In [ ]:
df.head()

   points  fruits
e     800   apple
f     450  orange
d     400   apple
b     300   apple
a     200  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [ ]:
d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

Print(d1)

In [ ]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [ ]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [ ]:
city = d1['city']

print city <br>
What is the type of city.

In [ ]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [ ]:
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})
print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [ ]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [ ]:
d3 = pd.concat([d1, d2], ignore_index=True)
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [ ]:
cities_low_temp = d3[d3['Temperature'] <= 20]
print(cities_low_temp)
print('Number of cities:', len(cities_low_temp))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [ ]:
cities_high_temp = d3[d3['Temperature'] >= 35]
print(cities_high_temp)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [ ]:
def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [ ]:
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [ ]:
def c_to_f(c):
    return (c * 9/5) + 32

In [ ]:
print(c_to_f(10))

50.0

In [ ]:
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
5    Bengalaru           24  False            75.2
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [ ]:
d1_ut = d1[d1['city'].isin(['Chandigarh', 'Pondicherry', 'Delhi'])]
print(d1_ut)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:
d1_above_90 = d1[d1['Temperature'].apply(c_to_f) > 90]
print(d1_above_90)

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [ ]:
print(d1.head(3))

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [ ]:
print(d3.iloc[:, -2:])

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
5  False            75.2
6  False            95.0
7  False            96.8
8   True           102.2

## Groupby

In [11]:
data = {
    'Branch': ['CSE', 'ECE', 'CSE', 'ECE', 'CSE', 'ECE', 'MECH', 'MECH'],
    'Year': [1, 1, 2, 2, 1, 2, 1, 2],
    'Students': [120, 100, 110, 90, 115, 95, 80, 85],
    'Placed': [90, 80, 95, 75, 88, 70, 60, 65]
}
df_groupby = pd.DataFrame(data)
print(df_groupby)

  Branch  Year  Students  Placed
0    CSE     1       120      90
1    ECE     1       100      80
2    CSE     2       110      95
3    ECE     2        90      75
4    CSE     1       115      88
5    ECE     2        95      70
6   MECH     1        80      60
7   MECH     2        85      65

In [ ]:
print(df_groupby.groupby('Branch')[['Students', 'Placed']].sum())

        Students  Placed
Branch
CSE          345     273
ECE          285     225
MECH         165     125

In [16]:
print(df_groupby.groupby('Branch')['Students'].count())

Branch
CSE     3
ECE     3
MECH    2
Name: Students, dtype: int64

In [ ]:
print(df_groupby.groupby('Branch')['Students'].agg(['min', 'max']))

        min  max
Branch
CSE     110  120
ECE      90  100
MECH     80   85

In [ ]:
print(df_groupby.groupby(['Branch', 'Year'])[['Students', 'Placed']].mean())

             Students  Placed
Branch Year
CSE    1        117.5    89.0
       2        110.0    95.0
ECE    1        100.0    80.0
       2         92.5    72.5
MECH   1         80.0    60.0
       2         85.0    65.0

In [ ]:
print(df_groupby.groupby(['Branch', 'Year'])['Placed'].agg(['min', 'max']))

             min  max
Branch Year
CSE    1      88   90
       2      95   95
ECE    1      80   80
       2      70   75
MECH   1      60   60
       2      65   65

In [ ]:
print('Groupby examples completed.')

Groupby examples completed.

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [ ]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [ ]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [ ]:
print(len(a))

457

What is the type of a?

In [ ]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [ ]:
print('Assignment complete!')

Assignment complete!